version: "3.9"
services:
  db:
    image: postgres:15.0
    ports:
      - "15432:5432"
    env_file:
      - "database.env"
    volumes: 
      - db:/var/lib/postgresql/data
  load_data:
    build: load_data/.
    env_file:
      - "database.env"
    depends_on:
    - db
  api:
    build: api/.
    ports: 
      - "8000:8000"
    env_file:
      - "database.env"
    depends_on:
      - db
      - load_data
    healthcheck:
      test: curl --fail http://api:8000 || exit 1   
    retstart: on-failure

  app:
    build: app
    ports:
      - "3000:3000"

  test:
    build: test/.
    depends_on:
      api:
        condition: service_healthy

volumes: 
  db:
    driver: local