version: "3.9"
services:
  api:
    build: api/.
    ports: 
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1   

  test:
    build: test/.
    depends_on:
      api:
        condition: service_healthy