name: Test API
on:
  push:
    paths:
      - "api/**"
      - "test/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker compose build test
      - name: Test
        run: docker compose up test

